#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#
# PROMOX INIT INFRASTRUCTURE - ADMIN
#
#   hostname : testing-wazuh-client
#   vm_id    : 1100
#   cpu core : 1
#   ram      : 2g
#   disk     : 24g
#   ip       : 192.168.42.110
#
#   template : template-vm-micro-01-2g-24g - id 9211
#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# TEST FILE  - issue #10

- hosts: px-testing
  gather_facts: false
  vars_files:
    - "../../../secrets/px-testing.cr42_tailscale.yml"

  vars:
    # global_vm_ssh_name: "cr42.testing-wazuh-client"
    # #
    # global_vm_id: 1110
    # global_vm_name: "testing-wazuh-client"
    # global_vm_description: ""
    # global_vm_tag_name: "admin"
    # global_vm_ci_ip: "192.168.42.110"
    # #
    # global_template_vm_id: 9211
    # global_template_name: "01-template-vm-micro-01-2g-24g - id 9211" # debug

  tasks:
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    - name: ADMIN INFRASTRUCTURE INIT - "{{ global_vm_name }}" - CLONE TEMPLATE - "{{ global_template_name }}"

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        proxmox_vm_action: "vm_clone"
        vm_id: "{{ global_template_vm_id }}" # TEMPLATE VM_ID - vars should be rename to vm_id_src / vm_id_dst
        vm_new_id: "{{ global_vm_id }}"
        vm_name: "{{ global_vm_name }}"
        vm_description: "{{ global_vm_description }}"

    - name: ADMIN INFRASTRUCTURE INIT - "{{ global_vm_name }}" - SET PROMOX TAG

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        proxmox_vm_action: "vm_set_tag"
        vm_id: "{{ global_vm_id }}"
        vm_tag_name: "{{ global_vm_tag_name }}"

    #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    - name: ADMIN INFRASTRUCTURE INIT - "{{ global_vm_name }}" - SET CLOUD DEFAULT INIT VARIABLE

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        proxmox_vm_action: "cloudinit_set_variables"

        vm_id: "{{ global_vm_id }}"
        vm_ci_user: "{{ default_admin_vm_ci_user | default('alice') }}"
        vm_ci_password: "{{ default_admin_vm_ci_password | default('supersecret') }}"
        vm_ci_ssh_key: "{{ default_admin_vm_ci_ssh_key  }}"
        vm_ci_namerserver_ips: "1.1.1.1"
        vm_ci_ip: "{{ global_vm_ci_ip }}"
        vm_ci_netmask: "24"
        vm_ci_ip_gw: "192.168.42.1"

    #
    - name: ADMIN INFRASTRUCTURE INIT - "{{ global_vm_name }}" - CLONE TEMPLATE - START VM

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        proxmox_vm_action: "vm_start"
        vm_id: "{{ global_vm_id }}"

    # #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- hosts: "{{ global_vm_ssh_name }}"
  gather_facts: false
  vars_files:
    - "../../../secrets/px-testing.cr42_tailscale.yml"

  vars:
    ARG_operator_ssh_config_known_hosts: "{{ VAULT_operator_ssh_config_known_hosts }}"
    ARG_vm_ssh_name: "{{ global_vm_ssh_name }}"

    requested_tasks:
      - wait/openssh_server/is_reachable.yml
      - wait/cloudinit/is_boot_finished.yml
  tasks:
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    - name: TASK DYNAMIC INCLUDE FROM ansible.utils
      include_role:
        name: ansible.utils
