#

- name: actions on virtual machines
  # hosts: "{{ proxmox_node }}"
  hosts: px-testing
  gather_facts: false

  vars_files:
    - "../../../secret/px-testing.cr42_tailscale.yaml"

  vars:
    proxmox_node: "px-testing"
    vm_ids:
      - 3001

  tasks:
    - name: "actions :: {{ proxmox_vm_action}} - all virtual machine"

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        vm_id: "{{ item }}"
        proxmox_node: "{{ proxmox_node }}"
        proxmox_vm_action: "{{ proxmox_vm_action}}"

      loop: "{{ vm_ids }}"
      loop_control:
        label: "vm_id={{ item }}"
