#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### STAGE 01  #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#


- name: install basics packages
  hosts: r42_init_vm_group
  become: true
  roles:
    - software.install.warmup.basic_packages

  #
  # variables will be overwrited by values  in _main.yml
  #

  vars:
    INSTALL_PACKAGES_BASICS: "YES"
    INSTALL_PACKAGES_FIREWALLS: "YES"
    #
    INSTALL_PACKAGES_DOCKER: "NO"
    INSTALL_PACKAGES_DOCKER_COMPOSE: "NO"
    #
    INSTALL_PACKAGES_UTILS_JSON: "NO"
    INSTALL_PACKAGES_UTILS_NETWORK: "YES"

    INSTALL_PACKAGES_NTP_AND_UPDATE_TIME: "YES"
    #
    # SPECIFIC_PACKAGES_CLEANING: "NO"
# #
# #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
# #

- name: install dot files
  hosts: r42_init_vm_group
  become: true
  roles:
    - software.install.warmup.dot_files

  vars:
    #
    # variables will be overwrited by values  in _main.yml
    #
    OPERATOR_USER: alice
    INSTALL_VIM_DOTFILES: "YES"
    INSTALL_ZSH_DOTFILES: "YES"

- name: configure firewall - all
  become: true
  hosts: r42_init_vm_group
  roles:
    - software.configure.firewalls

  #
  # variables will be overwrited by values  in _main.yml

  vars:
    firewall_rules:
      - ip: "all"
        port: 22
        protocol: "tcp"
#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#
