# - name: configure firewall - all
#   become: true
#   hosts: r42.vuln-box-02
#   roles:
#     - software.configure.firewalls

#   vars:
#     # variables will be overwrited by values  in _main.yml
#     firewall_rules:
#       - ip: "all"
#         port: 22
#         protocol: "tcp"
#       - ip: "all"
#         port: 21
#         protocol: "tcp"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: DOCKER FTP ANONYMOUS SERVER
  hosts: r42.vuln-box-03
  become: true
  roles:
    - software.configure.docker-compose
  vars_files:
    - "../../secrets/px-testing.cr42_tailscale.yml"
  vars:
    LABEL_PROJECT_TYPE: "CTF"
    LABEL_PROJET_NAME: "lpe-01"

    #
    LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/misconfiguration/system/lpe-01/"
    REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
    #

    OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
    #
    CLEAN_UP_DEPLOY_DIR: "NO"
    SEND_POC_DIR: "NO"
