#

- name: actions on virtual machines
  hosts: "px-testing"
  gather_facts: false

  vars_files:
    - "../../../../../../../scenarios/demo_lab/secrets/px-testing.cr42_tailscale.yml"

  vars:
    # PROXMOX_VM_ACTION: "vm_pause"
    # PROXMOX_VM_ACTION: "vm_stop"
    # PROXMOX_VM_ACTION: "vm_start"
    PROXMOX_VM_ACTION: "vm_resume"
    PROXMODE_NODE: "px-testing"
    VM_IDS:
      - 1000
      - 1020
      - 1021
      - 1023
      - 1022

  tasks:
    - name: "actions - {{ PROXMOX_VM_ACTION }} all virtual machine"

      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        vm_id: "{{ item }}"
        proxmox_node: "{{ PROXMODE_NODE }}"
        proxmox_vm_action: "{{ PROXMOX_VM_ACTION }}"

      loop: "{{ VM_IDS }}"
      loop_control:
        label: "vm_id={{ item }}"
