##
## ISSUE 12
##

## place holder

- name: configure firewall - all
  become: true
  hosts: r42.student-box-01
  roles:
    - software.configure.firewalls

  vars:
    firewall_rules:
      - ip: "all"
        port: 22
        protocol: "tcp"
  #
  # variables will be overwrited by values  in _main.yml
  #
