#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#
# PROMOX INIT - create ubuntu noble template :
#
#   vm_id    : 9211
#   cpu core : 1
#   ram      : 2g
#   disk     : 24g
#   ip       : 192.168.42.211
#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

##
## ISSUE - 
##

- hosts: proxmox
  gather_facts: false
  vars_files:
    - "../../../../secrets/default_vault.yml"

  tasks:
    #
    - name: PROMOX INIT - TEMPLATES - CREATE TEMPLATE - template-vm-micro-01-2g-24g
      include_role:
        name: range42-ansible_roles-proxmox_controller
      vars:
        proxmox_vm_action: "vm_create"
        # proxmox_node: "px-testing"
        vm_id: 9211
        vm_name: "template-vm-micro-01-2g-24g"
        vm_cpu: "host"
        vm_cores: 1
        vm_sockets: 1
        vm_memory: 2048
        vm_net_virtio_bridge: "vmbr142"

    #
    - name: PROMOX INIT - TEMPLATES - CONVERT VM TO TEMPLATE - template-vm-micro-01-2g-24g
      include_role:
        name: range42-ansible_roles-proxmox_controller
      vars:
        proxmox_vm_action: "template_convert_vm_to_template"
        # proxmox_node: "px-testing"
        proxmox_storage: "local"
        vm_id: 9211

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- hosts: proxmox-cli
  gather_facts: false
  vars_files:
    - "../../../../secrets/default_vault.yml"

  tasks:
    #
    - name: PROMOX INIT - TEMPLATES - IMPORT CLOUD INIT DISK - template-vm-micro-01-2g-24g
      include_role:
        name: range42-ansible_roles-proxmox_controller
      vars:
        proxmox_vm_action: "template_cloudinit_import_disk"
        # proxmox_node: "px-testing-cli"
        cloudinit_image_full_path: "/var/lib/vz/template/iso/noble-minimal-cloudimg-amd64.img"
        vm_id: 9211
        vm_disk_size: "24g"
        proxmox_dest_vm_storage_name: "local-lvm"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- hosts: proxmox
  gather_facts: false
  vars_files:
    - "../../../../secrets/default_vault.yml"

  tasks:
    #
    - name: PROMOX INIT - TEMPLATES - SET CLOUD DEFAULT INIT VARIABLE - template-vm-micro-01-2g-24g
      include_role:
        name: range42-ansible_roles-proxmox_controller
      vars:
        proxmox_vm_action: "cloudinit_set_variables"
        # proxmox_node: "px-testing"
        vm_id: 9211
        vm_ci_user: "{{ default_admin_vm_ci_user | default('alice') }}"
        vm_ci_password: "{{ default_trainee_vm_ci_password | default('supersecret') }}"
        vm_ci_ssh_key: "{{ default_trainee_vm_ci_ssh_key  }}"
        vm_ci_namerserver_ips: "1.1.1.1"
        vm_ci_ip: "192.168.42.211"
        vm_ci_netmask: "24"
        vm_ci_ip_gw: "192.168.42.1"

    #
    - name: PROMOX INIT - TEMPLATES - SET PROMOX TAG - template-vm-micro-01-2g-24g
      include_role:
        name: range42-ansible_roles-proxmox_controller
      vars:
        proxmox_vm_action: "vm_set_tag"
        # proxmox_node: "px-testing"
        vm_id: 9211
        vm_tag_name: "template"
