#

- name: actions on virtual machines
  # hosts: "{{ proxmox_node }}"
  hosts: proxmox # should be rename to px-api
  gather_facts: false

  vars_files:
    - "../../../../../../../scenarios/demo_lab/secrets/default_vault.yml"

  vars:
    PROXMOX_NODE: "px-testing"
    VMS:
      - ID: 1000
        NAME: "admin-wazuh"

      - ID: 1020
        NAME: "admin-web-api-kong"

      - ID: 1021
        NAME: "admin-web-builder-api"

      - ID: 1022
        NAME: "admin-web-emp"

      - ID: 1023
        NAME: "admin-web-deployer-ui"

      # - { id: 4001, name: "vm-lab-4001" }
      # - { id: 4002, name: "vm-lab-4002" }

  tasks:
    - name: "actions - force stop - virtual machine"
      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        vm_id: "{{ item.ID }}"
        proxmox_node: "{{ PROXMOX_NODE }}"
        proxmox_vm_action: "vm_stop_force"

      loop: "{{ VMS }}"
      loop_control:
        label: "vm_id={{ item.ID }} vm_name={{ item.NAME }}"

    #
    # - debug:
    #     msg: "ID={{ item.ID }} NAME={{ item.NAME }}"
    #   loop: "{{ VMS }}"
    # #

    - name: "actions - delete - virtual machine"
      include_role:
        name: range42-ansible_roles-proxmox_controller

      vars:
        vm_id: "{{ item.ID}}"
        vm_name: "{{ item.NAME }}" # required for the role - used to generate json reply
        proxmox_node: "{{ PROXMOX_NODE }}"
        proxmox_vm_action: "vm_delete"

      loop: "{{ VMS }}"
      loop_control:
        label: "vm_id={{ item.ID }} vm_name={{ item.NAME }}"
