##
## ISSUE 13
##

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: configure firewall - all
#   become: true
#   hosts: vuln-box-01
#   roles:
#     - software.configure.firewalls

#   vars:
#     # variables will be overwrited by values  in _main.yml
#     firewall_rules:
#       - ip: "all"
#         port: 22
#         protocol: "tcp"
#       - ip: "all"
#         port: 443
#         protocol: "tcp"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: DEPLOY - cve/crypto/openssl/CVE-2014-0160/"
#   hosts: r42.vuln-box-01
#   become: true
#   roles:
#     - software.configure.docker-compose

#   vars_files:
#     - "../../secrets/px-testing.cr42_tailscale.yml"
#   vars:
#     LABEL_PROJECT_TYPE: "CTF"
#     LABEL_PROJET_NAME: "crypto-openssl-cve-2014-0160"
#     #
#     LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/cve/crypto/openssl/CVE-2014-0160/"
#     # REMOTE_PROJECT_DIR: "/tmp/deploy"
#     REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
#     #
#     OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
#     #
#     CLEAN_UP_DEPLOY_DIR: "NO"
#     SEND_POC_DIR: "YES"

# ### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: DEPLOY - crypto-openssl-cve-2022-0778
#   hosts: r42.vuln-box-01
#   become: true
#   roles:
#     - software.configure.docker-compose

#   vars_files:
#     - "../../secrets/px-testing.cr42_tailscale.yml"
#   vars:
#     LABEL_PROJECT_TYPE: "CTF"
#     LABEL_PROJET_NAME: "crypto-openssl-cve-2022-0778"
#     #
#     LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/cve/crypto/openssl/CVE-2022-0778/"
#     REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
#     #
#     OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
#     #
#     CLEAN_UP_DEPLOY_DIR: "NO"
#     SEND_POC_DIR: "YES"

# ### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: DEPLOY - tomcat-cve-2025-24813
#   hosts: r42.vuln-box-01
#   become: true
#   roles:
#     - software.configure.docker-compose

#   vars_files:
#     - "../../secrets/px-testing.cr42_tailscale.yml"
#   vars:
#     LABEL_PROJECT_TYPE: "CTF"
#     LABEL_PROJET_NAME: "tomcat-cve-2025-24813"
#     #
#     LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/cve/web/tomcat/CVE-2025-24813/"
#     REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
#     #
#     OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
#     #
#     CLEAN_UP_DEPLOY_DIR: "NO"
#     SEND_POC_DIR: "YES"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: DEPLOY - apache-cve-2021-42013
#   hosts: r42.vuln-box-01
#   become: true
#   roles:
#     - software.configure.docker-compose

#   vars_files:
#     - "../../secrets/px-testing.cr42_tailscale.yml"
#   vars:
#     LABEL_PROJECT_TYPE: "CTF"
#     LABEL_PROJET_NAME: "apache-cve-2021-42013"
#     #
#     LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/cve/web/apache/CVE-2021-42013/"
#     REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
#     #
#     OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
#     #
#     CLEAN_UP_DEPLOY_DIR: "NO"
#     SEND_POC_DIR: "YES"


#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: DEPLOY - openssh-cve-2018-15473
  hosts: r42.vuln-box-01
  become: true
  roles:
    - software.configure.docker-compose

  vars_files:
    - "../../secrets/px-testing.cr42_tailscale.yml"
  vars:
    LABEL_PROJECT_TYPE: "CTF"
    LABEL_PROJET_NAME: "openssh-cve-2018-15473"
    #
    LOCAL__PROJECT_DIR: "{{ lookup('env', 'RANGE42_INVENTORY__DOCKER__CTF') }}/cve/network/openssh/CVE-2018-15473"
    REMOTE_PROJECT_DIR: "/tmp/deploy-{{ LABEL_PROJET_NAME }}"
    #
    OPERATOR_USER: "{{ default_admin_vm_ci_user }}"
    #
    CLEAN_UP_DEPLOY_DIR: "NO"
    SEND_POC_DIR: "YES"
    
