#

- name: install basics packages
  hosts: all
  become: true
  roles:
    # - software.install.warmup.dot_files
    - software.install.warmup.basic_packages

  #
  # variables will be overwrited by values coming from API
  #
  vars:
    # FOR - software.install.warmup.dot_files
    # OPERATOR_USER: jane
    # INSTALL_VIM_DOTFILES: "NO" # accept also true false
    # INSTALL_ZSH_DOTFILES: "NO" # accept also true false

    # FOR - software.install.warmup.basic_packages
    INSTALL_PACKAGES_BASICS: "YES"
    INSTALL_PACKAGES_FIREWALLS: "YES"
    #
    INSTALL_PACKAGES_DOCKER: "NO"
    INSTALL_PACKAGES_DOCKER_COMPOSE: "NO"
    #
    INSTALL_PACKAGES_UTILS_JSON: "NO"
    INSTALL_PACKAGES_UTILS_NETWORK: "NO"

    INSTALL_PACKAGES_NTP_AND_UPDATE_TIME: "YES"

    SPECIFIC_PACKAGES_CLEANING: "NO"
