#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#
# PREPARE VM for WAZUH TEST CLIENT AND TEST SERVER
#
#

# TEST FILE  - issue #10

- import_playbook: ./testing/wazuh_client_01.yaml

  vars:
    global_vm_name: "testing-wazuh-client"
    global_vm_ssh_name: "r42.testing-wazuh-client"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1111
    global_vm_description: "wazuh - client test"
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.111"
    #
    global_template_vm_id: 9211
    global_template_name: "01-template-vm-micro-01-2g-24g - id 9211" # debug
    #
    global_operator_ssh_config_known_hosts: "{{ GLOBAL_OPERATOR_SSH_CONFIG_KNOWN_HOSTS }}" # move this one to vault !

# #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./mon_wazuh.yaml

  vars:
    global_vm_name: "admin-wazuh"
    global_vm_ssh_name: "r42.admin-wazuh"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"

    global_vm_id: 1000
    global_vm_description: ""
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.100"
    #
    global_template_vm_id: 9232
    global_template_name: "03-template-vm-medium-02-8g-64g - 9232" # debug

    global_operator_ssh_config_known_hosts: "{{ GLOBAL_OPERATOR_SSH_CONFIG_KNOWN_HOSTS }}" # move this one to vault !

# #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: install updates - all
  hosts: r42_admin
  become: true
  roles:
    - software.install.updates

  vars:
    INSTALL_PACKAGES_NTP_AND_UPDATE_TIME: "NO"
    REBOOT_AFTER_UPDATES: "NO"

# ### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#
- name: install basics packages
  hosts: r42_admin
  become: true
  roles:
    - software.install.warmup.basic_packages

  vars:
    INSTALL_PACKAGES_BASICS: "YES"
    INSTALL_PACKAGES_FIREWALLS: "YES"
    #
    INSTALL_PACKAGES_DOCKER: "NO"
    INSTALL_PACKAGES_DOCKER_COMPOSE: "NO"
    #
    INSTALL_PACKAGES_UTILS_JSON: "YES"
    INSTALL_PACKAGES_UTILS_NETWORK: "YES"

    INSTALL_PACKAGES_NTP_AND_UPDATE_TIME: "YES"
    #

    SPECIFIC_PACKAGES_CLEANING: "NO"
# #
# #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
# #

- name: install dot files
  hosts: r42_admin
  become: true
  roles:
    - software.install.warmup.dot_files

  vars:
    OPERATOR_USER: alice

    INSTALL_VIM_DOTFILES: "YES"
    INSTALL_ZSH_DOTFILES: "YES"

- name: configure firewall - all
  become: true
  hosts: r42_admin
  roles:
    - software.configure.firewalls
  vars:
    firewall_rules:
      - ip: "all"
        port: 22
        protocol: "tcp"
#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#

- hosts: r42_admin
  become: true

  vars_files:
    - "../secrets/px-testing.cr42_tailscale.yaml"

  vars:
    tailscale_authkey: "{{ vault_tailscale_authkey }}"

  roles:
    - software.install.tailscale

- hosts: r42_admin
  become: true
  roles:
    - software.configure.tailscale_disable_nftables
  vars:
