#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

##
## ISSUE - 6
##

- import_playbook: ./testing/wazuh_client_01.yaml

  vars:
    global_vm_name: "testing-wazuh-client"
    global_vm_ssh_name: "r42.testing-wazuh-client"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1111
    global_vm_description: "wazuh - client test"
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.111"
    #
    global_template_vm_id: 9211
    global_template_name: "01-template-vm-micro-01-2g-24g - id 9211" # debug
    #
    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./mon_wazuh.yaml

  vars:
    global_vm_name: "admin-wazuh"
    global_vm_ssh_name: "r42.admin-wazuh"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"

    global_vm_id: 1000
    global_vm_description: ""
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.100"
    #
    global_template_vm_id: 9232
    global_template_name: "03-template-vm-medium-02-8g-64g - 9232" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./builder_docker_registry.yaml

  vars:
    global_vm_name: "admin-builder-docker-registry"
    global_vm_ssh_name: "r42.admin-builder-docker-registry"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"

    global_vm_id: 1001
    global_vm_description: "docker registry"
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.101"
    #
    global_template_vm_id: 9232
    global_template_name: "03-template-vm-medium-02-8g-64g - 9232" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./builder_api_devkit.yaml

  vars:
    global_vm_name: "admin-builder-api-devkit"
    global_vm_ssh_name: "r42.admin-builder-api-devkit"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1002
    global_vm_description: "devkit tooling"
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.102"
    #
    global_template_vm_id: 9232
    global_template_name: "01-template-vm-micro-01-2g-24g - id 9232" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./web_api_kong.yaml

  vars:
    global_vm_name: "admin-web-api-kong"
    global_vm_ssh_name: "r42.admin-web-api-kong"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1020
    global_vm_description: "API gateway"
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.120"
    #
    global_template_vm_id: 9221
    global_template_name: "template-vm-small-01-4g-32g - id : 9221" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./web_builder_api.yaml

  vars:
    global_vm_name: "admin-web-builder-api"
    global_vm_ssh_name: "r42.admin-web-builder-api"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1021
    global_vm_description: "www - backend API  "
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.121"
    #
    global_template_vm_id: 9221
    global_template_name: "template-vm-small-01-4g-32g - id : 9221" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- import_playbook: ./web_emp.yaml

  vars:
    global_vm_name: "admin-web-emp"
    global_vm_ssh_name: "r42.admin-web-emp"
    # global_vm_ssh_name: "r42.{{ global_vm_name }}"
    global_vm_id: 1022
    global_vm_description: "fwww - front end - r42 - EMP "
    global_vm_tag_name: "admin"
    global_vm_ci_ip: "192.168.42.122"
    #
    global_template_vm_id: 9221
    global_template_name: "template-vm-small-01-4g-32g - id : 9221" # debug

    global_operator_ssh_config_known_hosts: "/home/grml/.ssh/known_hosts" # move this one to vault !

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: install dot files
  hosts: r42_admin
  become: true
  roles:
    - software.install.warmup.dot_files

  vars:
    OPERATOR_USER: alice

    INSTALL_VIM_DOTFILES: "YES"
    INSTALL_ZSH_DOTFILES: "YES"

- name: configure firewall - all
  become: true
  hosts: r42_admin
  roles:
    - software.configure.firewalls
  vars:
    firewall_rules:
      - ip: "all"
        port: 22
        protocol: "tcp"
- name: configure firewall - all
  become: true
  hosts: emp
  roles:
    - software.configure.firewalls
  vars:
    firewall_rules:
      - ip: "all"
        port: 22
        protocol: "tcp"
      - ip: "all"
        port: 443
        protocol: "tcp"

- name: execute systems.checks.overview - all
  hosts: r42_admin
  become: true
  roles:
    - systems.checks.overview
  vars:

- name: restart NTP
  hosts: r42_admin
  become: true
  roles:
    - service.reload.ntp
  vars:

# #
# #
- hosts: r42_admin
  become: true

  vars_files:
    - "../secrets/px-testing.cr42_tailscale.yaml"

  vars:
    tailscale_authkey: "{{ vault_tailscale_authkey }}"

  roles:
    - software.install.tailscale

- hosts: r42_admin
  become: true
  roles:
    - software.configure.tailscale_disable_nftables
  vars:
# - hosts: all
#   become: yes
#   become_user: root
#   roles:
#     - ./roles/software.install.wazuh_4.11.2/ansible-wazuh-agent
#   vars:
#     wazuh_managers:
#       - address: off-orange-wazuh.skate-eagle.ts.net
#         port: 1514
#         protocol: tcp
#         api_port: 55000
#         api_proto: "https"
#         api_user: wazuh
#         max_retries: 5
#         retry_interval: 5

